/** Notice * This file contains works from many authors under various (but compatible) licenses. Please see legal.txt for more information. **/
(function(){(window.wpCoreControlsBundle=window.wpCoreControlsBundle||[]).push([[1],{239:function(ke,id,e){e.r(id);var z=e(0);e.n(z);var y=e(21),n=e(8),db=e(4),f=e(56);id["default"]=function(a){function b(a){var b=[];for(a.wa();a.advance();){var e=a.Ea();"field"===e?b.push(String(a.V("name"))):console.warn("unrecognised field list element: "+e)}a.Oa();return b}function e(a,b){return b?"false"===a?!1:!0:"true"===a?!0:!1}function x(a,f){var h=a.Ea();switch(h){case "javascript":return{name:"JavaScript",javascript:a.current.textContent};
case "uri":return{name:"URI",uri:a.V("uri")};case "goto":h=null;a.wa();if(a.advance()){var r=a.V("fit");h={page:a.V("page"),fit:r};if("0"===h.page)console.warn("null page encountered in dest");else switch(f=f(Number(h.page)),r){case "Fit":case "FitB":break;case "FitH":case "FitBH":h.top=f.ia({x:0,y:a.V("top")||0}).y;break;case "FitV":case "FitBV":h.left=f.ia({x:a.V("left")||0,y:0}).x;break;case "FitR":r=f.ia({x:a.V("left")||0,y:a.V("top")||0});f=f.ia({x:a.V("right")||0,y:a.V("bottom")||0});f=new n.a(r.x,
r.y,f.x,f.y);h.top=f.aa;h.left=f.ea;h.bottom=f.ca;h.right=f.fa;break;case "XYZ":r=f.ia({x:a.V("left")||0,y:a.V("top")||0});h.top=r.y;h.left=r.x;h.zoom=a.V("zoom")||0;break;default:console.warn("unknown dest fit: "+r)}h={name:"GoTo",dest:h}}else console.PZ("missing dest in GoTo action");a.Oa();return h;case "submit-form":h={name:"SubmitForm",url:a.V("url"),format:a.V("format"),method:a.V("method")||"POST",exclude:e(a.V("exclude"),!1)};f=a.V("flags");h.flags=f?f.split(" "):[];for(a.wa();a.advance();)switch(f=
a.Ea(),f){case "fields":h.fields=b(a);break;default:console.warn("unrecognised submit-form child: "+f)}a.Oa();return h;case "reset-form":h={name:"ResetForm",exclude:e(a.V("exclude"),!1)};for(a.wa();a.advance();)switch(f=a.Ea(),f){case "fields":h.fields=b(a);break;default:console.warn("unrecognised reset-form child: "+f)}a.Oa();return h;case "hide":h={name:"Hide",hide:e(a.V("hide"),!0)};for(a.wa();a.advance();)switch(f=a.Ea(),f){case "fields":h.fields=b(a);break;default:console.warn("unrecognised hide child: "+
f)}a.Oa();return h;case "named":return{name:"Named",action:a.V("name")};default:console.warn("Encountered unexpected action type: "+h)}return null}function r(a,b,e){var f={};for(a.wa();a.advance();){var h=a.Ea();switch(h){case "action":h=a.V("trigger");if(b?-1!==b.indexOf(h):1){f[h]=[];for(a.wa();a.advance();){var n=x(a,e);Object(z.isNull)(n)||f[h].push(n)}a.Oa()}else console.warn("encountered unexpected trigger on field: "+h);break;default:console.warn("encountered unknown action child: "+h)}}a.Oa();
return f}function w(a){return"calculation-order"===a.Ea()?b(a):[]}function h(a){return new db.a(a.V("r")||0,a.V("g")||0,a.V("b")||0,a.V("a")||1)}function id(a,b){var e=a.V("name"),f=a.V("type")||"Type1",n=a.V("size"),r=b.ia({x:0,y:0});n=b.ia({x:Number(n),y:0});b=r.x-n.x;r=r.y-n.y;e={name:e,type:f,size:Math.sqrt(b*b+r*r)||0,strokeColor:[0,0,0],fillColor:[0,0,0]};for(a.wa();a.advance();)switch(f=a.Ea(),f){case "stroke-color":e.strokeColor=h(a);break;case "fill-color":e.fillColor=h(a);break;default:console.warn("unrecognised font child: "+
f)}a.Oa();return e}function ke(a,b){var e={border:{style:"Solid",width:1},backgroundColor:[],fieldName:a.V("field"),page:a.V("page"),index:a.V("index")||0,rotation:a.V("rotation")||0,flags:[]},f=a.V("appearance");f&&(e.appearance=f);(f=a.V("flags"))&&(e.flags=f.split(" "));for(a.wa();a.advance();)switch(f=a.Ea(),f){case "rect":var w=a,x=b(Number(e.page));f=x.ia({x:w.V("x1")||0,y:w.V("y1")||0});w=x.ia({x:w.V("x2")||0,y:w.V("y2")||0});f=new n.a(f.x,f.y,w.x,w.y);f.normalize();e.rect={x1:f.x1,y1:f.y1,
x2:f.x2,y2:f.y2};break;case "border":f=a;w={style:f.V("style")||"Solid",width:f.V("width")||1,color:[0,0,0]};for(f.wa();f.advance();)switch(x=f.Ea(),x){case "color":w.color=h(f);break;default:console.warn("unrecognised border child: "+x)}f.Oa();e.border=w;break;case "background-color":e.backgroundColor=h(a);break;case "actions":e.actions=r(a,"E X D U Fo Bl PO PC PV PI".split(" "),b);break;case "appearances":f=a;w=qe.Bi(e,"appearances");for(f.wa();f.advance();)if(x=f.Ea(),"appearance"===x){x=f.V("name");
var y=qe.Bi(w,x);x=f;for(x.wa();x.advance();){var z=x.Ea();switch(z){case "Normal":qe.Bi(y,"Normal").data=x.current.textContent;break;default:console.warn("unexpected appearance state: ",z)}}x.Oa()}else console.warn("unexpected appearances child: "+x);f.Oa();break;case "extra":f=a;w=b;x={};for(f.wa();f.advance();)switch(y=f.Ea(),y){case "font":x.font=id(f,w(1));break;default:console.warn("unrecognised extra child: "+y)}f.Oa();f=x;f.font&&(e.font=f.font);break;case "captions":w=a;f={};(x=w.V("Normal"))&&
(f.Normal=x);(x=w.V("Rollover"))&&(f.Rollover=x);(w=w.V("Down"))&&(f.Down=w);e.captions=f;break;default:console.warn("unrecognised widget child: "+f)}a.Oa();return e}function le(a){var b={value:a.V("value")};(a=a.V("display-value"))&&(b.displayValue=a);return b}function ye(b,e){var f=b.V("name"),h={type:b.V("type"),quadding:b.V("quadding")||"Left-justified",maxLen:b.V("max-len")||-1},n=b.V("flags");Object(z.isString)(n)&&(h.flags=n.split(" "));for(b.wa();b.advance();)switch(n=b.Ea(),n){case "actions":h.actions=
r(b,["C","F","K","V"],e);break;case "default-value":n=b;n.wa();n.advance();var w=n.current.textContent;n.Oa();h.defaultValue=w;break;case "font":h.font=id(b,e);break;case "options":n=b;w=[];for(n.wa();n.advance();){var x=n.Ea();switch(x){case "option":w.push(le(n));break;default:console.warn("unrecognised options child: "+x)}}n.Oa();h.options=w;break;default:console.warn("unknown field child: "+n)}b.Oa();return new a.Annotations.ga.oa(f,h)}function ue(a,b){switch(a.type){case "Tx":return new y.h(a,
b);case "Ch":return a.flags.get("Combo")?new y.c(a,b):new y.d(a,b);case "Btn":return a.flags.get("PushButton")?new y.e(a,b):a.flags.get("Radio")?new y.f(a,b):new y.b(a,b);case "Sig":return new y.g(a,b);default:console.warn("Unrecognised field type: "+a.type)}return null}function ve(a,b){var e={number:a.V("number")};for(a.wa();a.advance();){var f=a.Ea();switch(f){case "actions":e.actions=r(a,["O","C"],b);break;default:console.warn("unrecognised page child: "+f)}}a.Oa();return e}a.yf=a.yf||{};var qe=
a.yf;qe.GN={parse:function(a,b,e,h){var n=[],x={};a.wa();var y=[],z={},db=[];Object(f.a)(function(){if(a.advance()){var e=a.Ea();switch(e){case "calculation-order":y=w(a);break;case "document-actions":z=r(a,["Init","Open"],b);break;case "pages":e=[];for(a.wa();a.advance();){var f=a.Ea();switch(f){case "page":e.push(ve(a,b));break;default:console.warn("unrecognised page child: "+f)}}a.Oa();db=e;break;case "field":e=ye(a,b(1));x[e.name]=e;break;case "widget":f=ke(a,b);(e=x[f.fieldName])?(e=ue(e,f),
n.push(e)):console.warn("ignoring widget with no corresponding field data: "+f.fieldName);break;default:console.warn("Unknown element encountered in PDFInfo: "+e)}return!0}return!1},function(){a.Oa();e({calculationOrder:y,widgets:n,fields:x,documentActions:z,pages:db,custom:[]})},h)},bW:ye,fW:ke,$V:w}}(window)}}]);}).call(this || window)
